.dashDaq_js_metadata <- function() {
deps_metadata <- list(`dash_daq` = structure(list(name = "dash_daq",
version = "0.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~colorpicker.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDaq",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_daq` = structure(list(name = "dash_daq",
version = "0.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~slider.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDaq",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_daq` = structure(list(name = "dash_daq",
version = "0.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~colorpicker.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDaq",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_daq` = structure(list(name = "dash_daq",
version = "0.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async~slider.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDaq",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_daq` = structure(list(name = "dash_daq",
version = "0.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_daq.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashDaq",
all_files = FALSE), class = "html_dependency"))
return(deps_metadata)
}
